version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0-node
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.0-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: TimeTracker_api_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: "Setup custom environment variables"
          command: echo 'export secretkey="07cf4aa414a6eacbcb46a34c49b6c4745b1901dad04030b17c8b0d56fddfc4a28d8cacbf7d3cb25b334cafe1f179b787e36294d696896d9e9bd81079af5e3225"' >> $BASH_ENV
      - run:
          name: "What was my custom environment variable?"
          command: echo ${secretkey}
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - run: bundle exec rake spec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build